import { BOMItem } from "@/components/bom-table";

export const bomDataByRequestId: Record<string, BOMItem[]> = {
  "REQ-2024-001": [
    {
      id: "E-1",
      level: 1,
      system: "Electrical",
      incomingPartNo: "EL-1001",
      incomingRevision: "R1",
      incomingDesc: "Electrical Component 1",
      incomingQtyPerVehicle: 1,
      incomingVehicleEndItem: "NA",
      incomingCost: 5000,
      outgoingPartNo: "EL-0901",
      outgoingRevision: "R0",
      outgoingDesc: "Legacy Electrical Component 1",
      outgoingQtyPerVehicle: 1,
      outgoingVehicleEndItem: "NA",
      outgoingCost: 4000,
      status: "Modify",
      remarks: "Electrical update",
    },
    {
      id: "E-2",
      level: 1,
      system: "Electrical",
      incomingPartNo: "EL-1002",
      incomingRevision: "R1",
      incomingDesc: "Electrical Component 2",
      incomingQtyPerVehicle: 1,
      incomingVehicleEndItem: "NA",
      incomingCost: 5500,
      outgoingPartNo: "EL-0902",
      outgoingRevision: "R0",
      outgoingDesc: "Legacy Electrical Component 2",
      outgoingQtyPerVehicle: 1,
      outgoingVehicleEndItem: "NA",
      outgoingCost: 4400,
      status: "Modify",
      remarks: "Electrical update",
    },
    {
      id: "E-3",
      level: 1,
      system: "Electrical",
      incomingPartNo: "EL-1003",
      incomingRevision: "R1",
      incomingDesc: "Electrical Component 3",
      incomingQtyPerVehicle: 1,
      incomingVehicleEndItem: "NA",
      incomingCost: 6000,
      outgoingPartNo: "EL-0903",
      outgoingRevision: "R0",
      outgoingDesc: "Legacy Electrical Component 3",
      outgoingQtyPerVehicle: 1,
      outgoingVehicleEndItem: "NA",
      outgoingCost: 4800,
      status: "Modify",
      remarks: "Electrical update",
    },
    {
      id: "E-4",
      level: 1,
      system: "Electrical",
      incomingPartNo: "EL-1004",
      incomingRevision: "R1",
      incomingDesc: "Electrical Component 4",
      incomingQtyPerVehicle: 1,
      incomingVehicleEndItem: "NA",
      incomingCost: 6500,
      outgoingPartNo: "EL-0904",
      outgoingRevision: "R0",
      outgoingDesc: "Legacy Electrical Component 4",
      outgoingQtyPerVehicle: 1,
      outgoingVehicleEndItem: "NA",
      outgoingCost: 5200,
      status: "Modify",
      remarks: "Electrical update",
    },
    {
      id: "E-5",
      level: 1,
      system: "Electrical",
      incomingPartNo: "EL-1005",
      incomingRevision: "R1",
      incomingDesc: "Electrical Component 5",
      incomingQtyPerVehicle: 1,
      incomingVehicleEndItem: "NA",
      incomingCost: 7000,
      outgoingPartNo: "EL-0905",
      outgoingRevision: "R0",
      outgoingDesc: "Legacy Electrical Component 5",
      outgoingQtyPerVehicle: 1,
      outgoingVehicleEndItem: "NA",
      outgoingCost: 5600,
      status: "Modify",
      remarks: "Electrical update",
    },
    {
      id: "E-6",
      level: 1,
      system: "Electrical",
      incomingPartNo: "EL-1006",
      incomingRevision: "R1",
      incomingDesc: "Electrical Component 6",
      incomingQtyPerVehicle: 1,
      incomingVehicleEndItem: "NA",
      incomingCost: 7500,
      outgoingPartNo: "EL-0906",
      outgoingRevision: "R0",
      outgoingDesc: "Legacy Electrical Component 6",
      outgoingQtyPerVehicle: 1,
      outgoingVehicleEndItem: "NA",
      outgoingCost: 6000,
      status: "Modify",
      remarks: "Electrical update",
    },
    {
      id: "E-7",
      level: 1,
      system: "Electrical",
      incomingPartNo: "EL-1007",
      incomingRevision: "R1",
      incomingDesc: "Electrical Component 7",
      incomingQtyPerVehicle: 1,
      incomingVehicleEndItem: "NA",
      incomingCost: 8000,
      outgoingPartNo: "EL-0907",
      outgoingRevision: "R0",
      outgoingDesc: "Legacy Electrical Component 7",
      outgoingQtyPerVehicle: 1,
      outgoingVehicleEndItem: "NA",
      outgoingCost: 6400,
      status: "Modify",
      remarks: "Electrical update",
    },
    {
      id: "E-8",
      level: 1,
      system: "Electrical",
      incomingPartNo: "EL-1008",
      incomingRevision: "R1",
      incomingDesc: "Electrical Component 8",
      incomingQtyPerVehicle: 1,
      incomingVehicleEndItem: "NA",
      incomingCost: 8500,
      outgoingPartNo: "EL-0908",
      outgoingRevision: "R0",
      outgoingDesc: "Legacy Electrical Component 8",
      outgoingQtyPerVehicle: 1,
      outgoingVehicleEndItem: "NA",
      outgoingCost: 6800,
      status: "Modify",
      remarks: "Electrical update",
    },
    {
      id: "E-9",
      level: 1,
      system: "Electrical",
      incomingPartNo: "EL-1009",
      incomingRevision: "R1",
      incomingDesc: "Electrical Component 9",
      incomingQtyPerVehicle: 1,
      incomingVehicleEndItem: "NA",
      incomingCost: 9000,
      outgoingPartNo: "EL-0909",
      outgoingRevision: "R0",
      outgoingDesc: "Legacy Electrical Component 9",
      outgoingQtyPerVehicle: 1,
      outgoingVehicleEndItem: "NA",
      outgoingCost: 7200,
      status: "Modify",
      remarks: "Electrical update",
    },
    {
      id: "E-10",
      level: 1,
      system: "Electrical",
      incomingPartNo: "EL-1010",
      incomingRevision: "R1",
      incomingDesc: "Electrical Component 10",
      incomingQtyPerVehicle: 1,
      incomingVehicleEndItem: "NA",
      incomingCost: 9500,
      outgoingPartNo: "EL-0910",
      outgoingRevision: "R0",
      outgoingDesc: "Legacy Electrical Component 10",
      outgoingQtyPerVehicle: 1,
      outgoingVehicleEndItem: "NA",
      outgoingCost: 7600,
      status: "Modify",
      remarks: "Electrical update",
    },
  ],
  "REQ-2024-002": [
  {
    id: "C-1",
    level: 1,
    system: "Chassis",
    incomingPartNo: "CH-71020",
    incomingRevision: "R1",
    incomingDesc: "Reinforced Rear Axle Beam",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 15000,
    outgoingPartNo: "CH-71005",
    outgoingRevision: "R0",
    outgoingDesc: "Rear Axle Beam",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 10000,
    status: "Modify",
    remarks: "NVH and durability improvement",
  },
  {
    id: "C-2",
    level: 1,
    system: "Chassis",
    incomingPartNo: "CH-72015",
    incomingRevision: "R1",
    incomingDesc: "Hydraulic Suspension Bushing",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 1800,
    outgoingPartNo: "CH-72001",
    outgoingRevision: "R0",
    outgoingDesc: "Rubber Suspension Bushing",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 900,
    status: "Modify",
    remarks: "Ride comfort enhancement",
  },
  {
    id: "C-3",
    level: 1,
    system: "Chassis",
    incomingPartNo: "CH-73040",
    incomingRevision: "R1",
    incomingDesc: "High-strength Front Subframe",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 22000,
    outgoingPartNo: "CH-73010",
    outgoingRevision: "R0",
    outgoingDesc: "Standard Front Subframe",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 17000,
    status: "Modify",
    remarks: "Improved crash performance",
  },
  {
    id: "C-4",
    level: 1,
    system: "Chassis",
    incomingPartNo: "CH-74018",
    incomingRevision: "R1",
    incomingDesc: "Rear Stabilizer Bar – Increased Dia",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 3200,
    outgoingPartNo: "CH-74005",
    outgoingRevision: "R0",
    outgoingDesc: "Rear Stabilizer Bar",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 2200,
    status: "Modify",
    remarks: "Reduced body roll",
  },
  {
    id: "C-5",
    level: 1,
    system: "Chassis",
    incomingPartNo: "CH-75022",
    incomingRevision: "R1",
    incomingDesc: "Aluminium Lower Control Arm",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 7800,
    outgoingPartNo: "CH-75001",
    outgoingRevision: "R0",
    outgoingDesc: "Steel Lower Control Arm",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 5200,
    status: "Modify",
    remarks: "Unsprung mass reduction",
  },
  {
    id: "C-6",
    level: 1,
    system: "Chassis",
    incomingPartNo: "CH-76009",
    incomingRevision: "R1",
    incomingDesc: "Rear Torsion Beam Mount",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 2600,
    outgoingPartNo: "CH-76001",
    outgoingRevision: "R0",
    outgoingDesc: "Standard Beam Mount",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 1800,
    status: "Modify",
    remarks: "Improved lateral stiffness",
  },
  {
    id: "C-7",
    level: 1,
    system: "Chassis",
    incomingPartNo: "CH-77014",
    incomingRevision: "R1",
    incomingDesc: "High-load Wheel Hub Assembly",
    incomingQtyPerVehicle: 4,
    incomingVehicleEndItem: "NA",
    incomingCost: 6400,
    outgoingPartNo: "CH-77002",
    outgoingRevision: "R0",
    outgoingDesc: "Standard Wheel Hub Assembly",
    outgoingQtyPerVehicle: 4,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 4800,
    status: "Modify",
    remarks: "Supports higher GVW",
  },
  {
    id: "C-8",
    level: 1,
    system: "Chassis",
    incomingPartNo: "CH-78006",
    incomingRevision: "R1",
    incomingDesc: "Upgraded Shock Absorber",
    incomingQtyPerVehicle: 4,
    incomingVehicleEndItem: "NA",
    incomingCost: 9200,
    outgoingPartNo: "CH-78001",
    outgoingRevision: "R0",
    outgoingDesc: "Standard Shock Absorber",
    outgoingQtyPerVehicle: 4,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 6800,
    status: "Modify",
    remarks: "Improved damping characteristics",
  },
  {
    id: "C-9",
    level: 1,
    system: "Chassis",
    incomingPartNo: "CH-79011",
    incomingRevision: "R1",
    incomingDesc: "Front Cross Member Reinforcement",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 5400,
    outgoingPartNo: "CH-79001",
    outgoingRevision: "R0",
    outgoingDesc: "Front Cross Member",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 3900,
    status: "Modify",
    remarks: "Steering feel improvement",
  },
  {
    id: "C-10",
    level: 1,
    system: "Chassis",
    incomingPartNo: "CH-79505",
    incomingRevision: "R1",
    incomingDesc: "Underbody Structural Brace",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 4100,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Improved torsional rigidity",
  },
],

  "REQ-2024-003": [
  {
    id: "I-1",
    level: 1,
    system: "Interiors",
    incomingPartNo: "IN-3001",
    incomingRevision: "R2",
    incomingDesc: "Interior Component 1",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 3000,
    outgoingPartNo: "IN-2901",
    outgoingRevision: "R1",
    outgoingDesc: "Legacy Interior Component 1",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 2200,
    status: "Modify",
    remarks: "Interior upgrade",
  },
  {
    id: "I-2",
    level: 1,
    system: "Interiors",
    incomingPartNo: "IN-3002",
    incomingRevision: "R2",
    incomingDesc: "Interior Component 2",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 3300,
    outgoingPartNo: "IN-2902",
    outgoingRevision: "R1",
    outgoingDesc: "Legacy Interior Component 2",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 2500,
    status: "Modify",
    remarks: "Interior upgrade",
  },
  {
    id: "I-3",
    level: 1,
    system: "Interiors",
    incomingPartNo: "IN-3003",
    incomingRevision: "R2",
    incomingDesc: "Interior Component 3",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 3600,
    outgoingPartNo: "IN-2903",
    outgoingRevision: "R1",
    outgoingDesc: "Legacy Interior Component 3",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 2800,
    status: "Modify",
    remarks: "Interior upgrade",
  },
  {
    id: "I-4",
    level: 1,
    system: "Interiors",
    incomingPartNo: "IN-3004",
    incomingRevision: "R2",
    incomingDesc: "Interior Component 4",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 3900,
    outgoingPartNo: "IN-2904",
    outgoingRevision: "R1",
    outgoingDesc: "Legacy Interior Component 4",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 3100,
    status: "Modify",
    remarks: "Interior upgrade",
  },
  {
    id: "I-5",
    level: 1,
    system: "Interiors",
    incomingPartNo: "IN-3005",
    incomingRevision: "R2",
    incomingDesc: "Interior Component 5",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 4200,
    outgoingPartNo: "IN-2905",
    outgoingRevision: "R1",
    outgoingDesc: "Legacy Interior Component 5",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 3400,
    status: "Modify",
    remarks: "Interior upgrade",
  },
  {
    id: "I-6",
    level: 1,
    system: "Interiors",
    incomingPartNo: "IN-3006",
    incomingRevision: "R2",
    incomingDesc: "Interior Component 6",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 4500,
    outgoingPartNo: "IN-2906",
    outgoingRevision: "R1",
    outgoingDesc: "Legacy Interior Component 6",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 3700,
    status: "Modify",
    remarks: "Interior upgrade",
  },
  {
    id: "I-7",
    level: 1,
    system: "Interiors",
    incomingPartNo: "IN-3007",
    incomingRevision: "R2",
    incomingDesc: "Interior Component 7",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 4800,
    outgoingPartNo: "IN-2907",
    outgoingRevision: "R1",
    outgoingDesc: "Legacy Interior Component 7",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 4000,
    status: "Modify",
    remarks: "Interior upgrade",
  },
  {
    id: "I-8",
    level: 1,
    system: "Interiors",
    incomingPartNo: "IN-3008",
    incomingRevision: "R2",
    incomingDesc: "Interior Component 8",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 5100,
    outgoingPartNo: "IN-2908",
    outgoingRevision: "R1",
    outgoingDesc: "Legacy Interior Component 8",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 4300,
    status: "Modify",
    remarks: "Interior upgrade",
  },
  {
    id: "I-9",
    level: 1,
    system: "Interiors",
    incomingPartNo: "IN-3009",
    incomingRevision: "R2",
    incomingDesc: "Interior Component 9",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 5400,
    outgoingPartNo: "IN-2909",
    outgoingRevision: "R1",
    outgoingDesc: "Legacy Interior Component 9",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 4600,
    status: "Modify",
    remarks: "Interior upgrade",
  },
  {
    id: "I-10",
    level: 1,
    system: "Interiors",
    incomingPartNo: "IN-3010",
    incomingRevision: "R2",
    incomingDesc: "Interior Component 10",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 5700,
    outgoingPartNo: "IN-2910",
    outgoingRevision: "R1",
    outgoingDesc: "Legacy Interior Component 10",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 4900,
    status: "Modify",
    remarks: "Interior upgrade",
  },
],
"REQ-2024-004": [
  {
    id: "P-1",
    level: 1,
    system: "Powertrain",
    incomingPartNo: "PT-4001",
    incomingRevision: "R1",
    incomingDesc: "Powertrain Component 1",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 15000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Powertrain expansion",
  },
  {
    id: "P-2",
    level: 1,
    system: "Powertrain",
    incomingPartNo: "PT-4002",
    incomingRevision: "R1",
    incomingDesc: "Powertrain Component 2",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 16000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Powertrain expansion",
  },
  {
    id: "P-3",
    level: 1,
    system: "Powertrain",
    incomingPartNo: "PT-4003",
    incomingRevision: "R1",
    incomingDesc: "Powertrain Component 3",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 17000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Powertrain expansion",
  },
  {
    id: "P-4",
    level: 1,
    system: "Powertrain",
    incomingPartNo: "PT-4004",
    incomingRevision: "R1",
    incomingDesc: "Powertrain Component 4",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 18000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Powertrain expansion",
  },
  {
    id: "P-5",
    level: 1,
    system: "Powertrain",
    incomingPartNo: "PT-4005",
    incomingRevision: "R1",
    incomingDesc: "Powertrain Component 5",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 19000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Powertrain expansion",
  },
  {
    id: "P-6",
    level: 1,
    system: "Powertrain",
    incomingPartNo: "PT-4006",
    incomingRevision: "R1",
    incomingDesc: "Powertrain Component 6",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 20000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Powertrain expansion",
  },
  {
    id: "P-7",
    level: 1,
    system: "Powertrain",
    incomingPartNo: "PT-4007",
    incomingRevision: "R1",
    incomingDesc: "Powertrain Component 7",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 21000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Powertrain expansion",
  },
  {
    id: "P-8",
    level: 1,
    system: "Powertrain",
    incomingPartNo: "PT-4008",
    incomingRevision: "R1",
    incomingDesc: "Powertrain Component 8",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 22000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Powertrain expansion",
  },
  {
    id: "P-9",
    level: 1,
    system: "Powertrain",
    incomingPartNo: "PT-4009",
    incomingRevision: "R1",
    incomingDesc: "Powertrain Component 9",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 23000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Powertrain expansion",
  },
  {
    id: "P-10",
    level: 1,
    system: "Powertrain",
    incomingPartNo: "PT-4010",
    incomingRevision: "R1",
    incomingDesc: "Powertrain Component 10",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 24000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Powertrain expansion",
  },
],
"REQ-2024-005": [
  {
    id: "S-1",
    level: 1,
    system: "Safety",
    incomingPartNo: "SF-5001",
    incomingRevision: "R1",
    incomingDesc: "Safety Component 1",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 4200,
    outgoingPartNo: "SF-4901",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Safety Component 1",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 3200,
    status: "Modify",
    remarks: "Safety compliance update",
  },
  {
    id: "S-2",
    level: 1,
    system: "Safety",
    incomingPartNo: "SF-5002",
    incomingRevision: "R1",
    incomingDesc: "Safety Component 2",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 4550,
    outgoingPartNo: "SF-4902",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Safety Component 2",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 3500,
    status: "Modify",
    remarks: "Safety compliance update",
  },
  {
    id: "S-3",
    level: 1,
    system: "Safety",
    incomingPartNo: "SF-5003",
    incomingRevision: "R1",
    incomingDesc: "Safety Component 3",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 4900,
    outgoingPartNo: "SF-4903",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Safety Component 3",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 3800,
    status: "Modify",
    remarks: "Safety compliance update",
  },
  {
    id: "S-4",
    level: 1,
    system: "Safety",
    incomingPartNo: "SF-5004",
    incomingRevision: "R1",
    incomingDesc: "Safety Component 4",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 5250,
    outgoingPartNo: "SF-4904",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Safety Component 4",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 4100,
    status: "Modify",
    remarks: "Safety compliance update",
  },
  {
    id: "S-5",
    level: 1,
    system: "Safety",
    incomingPartNo: "SF-5005",
    incomingRevision: "R1",
    incomingDesc: "Safety Component 5",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 5600,
    outgoingPartNo: "SF-4905",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Safety Component 5",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 4400,
    status: "Modify",
    remarks: "Safety compliance update",
  },
  {
    id: "S-6",
    level: 1,
    system: "Safety",
    incomingPartNo: "SF-5006",
    incomingRevision: "R1",
    incomingDesc: "Safety Component 6",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 5950,
    outgoingPartNo: "SF-4906",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Safety Component 6",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 4700,
    status: "Modify",
    remarks: "Safety compliance update",
  },
  {
    id: "S-7",
    level: 1,
    system: "Safety",
    incomingPartNo: "SF-5007",
    incomingRevision: "R1",
    incomingDesc: "Safety Component 7",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 6300,
    outgoingPartNo: "SF-4907",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Safety Component 7",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 5000,
    status: "Modify",
    remarks: "Safety compliance update",
  },
  {
    id: "S-8",
    level: 1,
    system: "Safety",
    incomingPartNo: "SF-5008",
    incomingRevision: "R1",
    incomingDesc: "Safety Component 8",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 6650,
    outgoingPartNo: "SF-4908",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Safety Component 8",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 5300,
    status: "Modify",
    remarks: "Safety compliance update",
  },
  {
    id: "S-9",
    level: 1,
    system: "Safety",
    incomingPartNo: "SF-5009",
    incomingRevision: "R1",
    incomingDesc: "Safety Component 9",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 7000,
    outgoingPartNo: "SF-4909",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Safety Component 9",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 5600,
    status: "Modify",
    remarks: "Safety compliance update",
  },
  {
    id: "S-10",
    level: 1,
    system: "Safety",
    incomingPartNo: "SF-5010",
    incomingRevision: "R1",
    incomingDesc: "Safety Component 10",
    incomingQtyPerVehicle: 2,
    incomingVehicleEndItem: "NA",
    incomingCost: 7350,
    outgoingPartNo: "SF-4910",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Safety Component 10",
    outgoingQtyPerVehicle: 2,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 5900,
    status: "Modify",
    remarks: "Safety compliance update",
  },
],
"REQ-2024-006": [
  {
    id: "B-1",
    level: 1,
    system: "Body",
    incomingPartNo: "BD-6001",
    incomingRevision: "R1",
    incomingDesc: "Body Component 1",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 7000,
    outgoingPartNo: "BD-5901",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Body Component 1",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 5600,
    status: "Modify",
    remarks: "Fit and finish improvement",
  },
  {
    id: "B-2",
    level: 1,
    system: "Body",
    incomingPartNo: "BD-6002",
    incomingRevision: "R1",
    incomingDesc: "Body Component 2",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 7500,
    outgoingPartNo: "BD-5902",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Body Component 2",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 6000,
    status: "Modify",
    remarks: "Fit and finish improvement",
  },
  {
    id: "B-3",
    level: 1,
    system: "Body",
    incomingPartNo: "BD-6003",
    incomingRevision: "R1",
    incomingDesc: "Body Component 3",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 8000,
    outgoingPartNo: "BD-5903",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Body Component 3",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 6400,
    status: "Modify",
    remarks: "Fit and finish improvement",
  },
  {
    id: "B-4",
    level: 1,
    system: "Body",
    incomingPartNo: "BD-6004",
    incomingRevision: "R1",
    incomingDesc: "Body Component 4",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 8500,
    outgoingPartNo: "BD-5904",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Body Component 4",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 6800,
    status: "Modify",
    remarks: "Fit and finish improvement",
  },
  {
    id: "B-5",
    level: 1,
    system: "Body",
    incomingPartNo: "BD-6005",
    incomingRevision: "R1",
    incomingDesc: "Body Component 5",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 9000,
    outgoingPartNo: "BD-5905",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Body Component 5",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 7200,
    status: "Modify",
    remarks: "Fit and finish improvement",
  },
  {
    id: "B-6",
    level: 1,
    system: "Body",
    incomingPartNo: "BD-6006",
    incomingRevision: "R1",
    incomingDesc: "Body Component 6",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 9500,
    outgoingPartNo: "BD-5906",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Body Component 6",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 7600,
    status: "Modify",
    remarks: "Fit and finish improvement",
  },
  {
    id: "B-7",
    level: 1,
    system: "Body",
    incomingPartNo: "BD-6007",
    incomingRevision: "R1",
    incomingDesc: "Body Component 7",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 10000,
    outgoingPartNo: "BD-5907",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Body Component 7",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 8000,
    status: "Modify",
    remarks: "Fit and finish improvement",
  },
  {
    id: "B-8",
    level: 1,
    system: "Body",
    incomingPartNo: "BD-6008",
    incomingRevision: "R1",
    incomingDesc: "Body Component 8",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 10500,
    outgoingPartNo: "BD-5908",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Body Component 8",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 8400,
    status: "Modify",
    remarks: "Fit and finish improvement",
  },
  {
    id: "B-9",
    level: 1,
    system: "Body",
    incomingPartNo: "BD-6009",
    incomingRevision: "R1",
    incomingDesc: "Body Component 9",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 11000,
    outgoingPartNo: "BD-5909",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Body Component 9",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 8800,
    status: "Modify",
    remarks: "Fit and finish improvement",
  },
  {
    id: "B-10",
    level: 1,
    system: "Body",
    incomingPartNo: "BD-6010",
    incomingRevision: "R1",
    incomingDesc: "Body Component 10",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 11500,
    outgoingPartNo: "BD-5910",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Body Component 10",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 9200,
    status: "Modify",
    remarks: "Fit and finish improvement",
  },
],
"REQ-2024-007": [
  {
    id: "T-1",
    level: 1,
    system: "Thermal",
    incomingPartNo: "TH-7001",
    incomingRevision: "R1",
    incomingDesc: "Thermal Component 1",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 4800,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Thermal performance upgrade",
  },
  {
    id: "T-2",
    level: 1,
    system: "Thermal",
    incomingPartNo: "TH-7002",
    incomingRevision: "R1",
    incomingDesc: "Thermal Component 2",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 5200,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Thermal performance upgrade",
  },
  {
    id: "T-3",
    level: 1,
    system: "Thermal",
    incomingPartNo: "TH-7003",
    incomingRevision: "R1",
    incomingDesc: "Thermal Component 3",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 5600,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Thermal performance upgrade",
  },
  {
    id: "T-4",
    level: 1,
    system: "Thermal",
    incomingPartNo: "TH-7004",
    incomingRevision: "R1",
    incomingDesc: "Thermal Component 4",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 6000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Thermal performance upgrade",
  },
  {
    id: "T-5",
    level: 1,
    system: "Thermal",
    incomingPartNo: "TH-7005",
    incomingRevision: "R1",
    incomingDesc: "Thermal Component 5",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 6400,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Thermal performance upgrade",
  },
  {
    id: "T-6",
    level: 1,
    system: "Thermal",
    incomingPartNo: "TH-7006",
    incomingRevision: "R1",
    incomingDesc: "Thermal Component 6",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 6800,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Thermal performance upgrade",
  },
  {
    id: "T-7",
    level: 1,
    system: "Thermal",
    incomingPartNo: "TH-7007",
    incomingRevision: "R1",
    incomingDesc: "Thermal Component 7",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 7200,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Thermal performance upgrade",
  },
  {
    id: "T-8",
    level: 1,
    system: "Thermal",
    incomingPartNo: "TH-7008",
    incomingRevision: "R1",
    incomingDesc: "Thermal Component 8",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 7600,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Thermal performance upgrade",
  },
  {
    id: "T-9",
    level: 1,
    system: "Thermal",
    incomingPartNo: "TH-7009",
    incomingRevision: "R1",
    incomingDesc: "Thermal Component 9",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 8000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Thermal performance upgrade",
  },
  {
    id: "T-10",
    level: 1,
    system: "Thermal",
    incomingPartNo: "TH-7010",
    incomingRevision: "R1",
    incomingDesc: "Thermal Component 10",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 8400,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Thermal performance upgrade",
  },
],
"REQ-2024-008": [
  {
    id: "A-1",
    level: 1,
    system: "ADAS",
    incomingPartNo: "AD-8001",
    incomingRevision: "R1",
    incomingDesc: "ADAS Component 1",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "N0",
    incomingCost: 12000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "ADAS feature expansion",
  },
  {
    id: "A-2",
    level: 1,
    system: "ADAS",
    incomingPartNo: "AD-8002",
    incomingRevision: "R1",
    incomingDesc: "ADAS Component 2",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "N0",
    incomingCost: 12900,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "ADAS feature expansion",
  },
  {
    id: "A-3",
    level: 1,
    system: "ADAS",
    incomingPartNo: "AD-8003",
    incomingRevision: "R1",
    incomingDesc: "ADAS Component 3",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "N0",
    incomingCost: 13800,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "ADAS feature expansion",
  },
  {
    id: "A-4",
    level: 1,
    system: "ADAS",
    incomingPartNo: "AD-8004",
    incomingRevision: "R1",
    incomingDesc: "ADAS Component 4",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "N0",
    incomingCost: 14700,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "ADAS feature expansion",
  },
  {
    id: "A-5",
    level: 1,
    system: "ADAS",
    incomingPartNo: "AD-8005",
    incomingRevision: "R1",
    incomingDesc: "ADAS Component 5",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "N0",
    incomingCost: 15600,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "ADAS feature expansion",
  },
  {
    id: "A-6",
    level: 1,
    system: "ADAS",
    incomingPartNo: "AD-8006",
    incomingRevision: "R1",
    incomingDesc: "ADAS Component 6",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "N0",
    incomingCost: 16500,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "ADAS feature expansion",
  },
  {
    id: "A-7",
    level: 1,
    system: "ADAS",
    incomingPartNo: "AD-8007",
    incomingRevision: "R1",
    incomingDesc: "ADAS Component 7",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "N0",
    incomingCost: 17400,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "ADAS feature expansion",
  },
  {
    id: "A-8",
    level: 1,
    system: "ADAS",
    incomingPartNo: "AD-8008",
    incomingRevision: "R1",
    incomingDesc: "ADAS Component 8",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "N0",
    incomingCost: 18300,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "ADAS feature expansion",
  },
  {
    id: "A-9",
    level: 1,
    system: "ADAS",
    incomingPartNo: "AD-8009",
    incomingRevision: "R1",
    incomingDesc: "ADAS Component 9",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "N0",
    incomingCost: 19200,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "ADAS feature expansion",
  },
  {
    id: "A-10",
    level: 1,
    system: "ADAS",
    incomingPartNo: "AD-8010",
    incomingRevision: "R1",
    incomingDesc: "ADAS Component 10",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "N0",
    incomingCost: 20100,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "ADAS feature expansion",
  },
],
"REQ-2024-009": [
  {
    id: "F-1",
    level: 1,
    system: "Fuel",
    incomingPartNo: "FL-9001",
    incomingRevision: "R1",
    incomingDesc: "Fuel System Component 1",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 6500,
    outgoingPartNo: "FL-8901",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Fuel Component 1",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 5200,
    status: "Modify",
    remarks: "Emission optimization",
  },
  {
    id: "F-2",
    level: 1,
    system: "Fuel",
    incomingPartNo: "FL-9002",
    incomingRevision: "R1",
    incomingDesc: "Fuel System Component 2",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 7000,
    outgoingPartNo: "FL-8902",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Fuel Component 2",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 5600,
    status: "Modify",
    remarks: "Emission optimization",
  },
  {
    id: "F-3",
    level: 1,
    system: "Fuel",
    incomingPartNo: "FL-9003",
    incomingRevision: "R1",
    incomingDesc: "Fuel System Component 3",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 7500,
    outgoingPartNo: "FL-8903",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Fuel Component 3",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 6000,
    status: "Modify",
    remarks: "Emission optimization",
  },
  {
    id: "F-4",
    level: 1,
    system: "Fuel",
    incomingPartNo: "FL-9004",
    incomingRevision: "R1",
    incomingDesc: "Fuel System Component 4",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 8000,
    outgoingPartNo: "FL-8904",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Fuel Component 4",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 6400,
    status: "Modify",
    remarks: "Emission optimization",
  },
  {
    id: "F-5",
    level: 1,
    system: "Fuel",
    incomingPartNo: "FL-9005",
    incomingRevision: "R1",
    incomingDesc: "Fuel System Component 5",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 8500,
    outgoingPartNo: "FL-8905",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Fuel Component 5",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 6800,
    status: "Modify",
    remarks: "Emission optimization",
  },
  {
    id: "F-6",
    level: 1,
    system: "Fuel",
    incomingPartNo: "FL-9006",
    incomingRevision: "R1",
    incomingDesc: "Fuel System Component 6",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 9000,
    outgoingPartNo: "FL-8906",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Fuel Component 6",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 7200,
    status: "Modify",
    remarks: "Emission optimization",
  },
  {
    id: "F-7",
    level: 1,
    system: "Fuel",
    incomingPartNo: "FL-9007",
    incomingRevision: "R1",
    incomingDesc: "Fuel System Component 7",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 9500,
    outgoingPartNo: "FL-8907",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Fuel Component 7",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 7600,
    status: "Modify",
    remarks: "Emission optimization",
  },
  {
    id: "F-8",
    level: 1,
    system: "Fuel",
    incomingPartNo: "FL-9008",
    incomingRevision: "R1",
    incomingDesc: "Fuel System Component 8",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 10000,
    outgoingPartNo: "FL-8908",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Fuel Component 8",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 8000,
    status: "Modify",
    remarks: "Emission optimization",
  },
  {
    id: "F-9",
    level: 1,
    system: "Fuel",
    incomingPartNo: "FL-9009",
    incomingRevision: "R1",
    incomingDesc: "Fuel System Component 9",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 10500,
    outgoingPartNo: "FL-8909",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Fuel Component 9",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 8400,
    status: "Modify",
    remarks: "Emission optimization",
  },
  {
    id: "F-10",
    level: 1,
    system: "Fuel",
    incomingPartNo: "FL-9010",
    incomingRevision: "R1",
    incomingDesc: "Fuel System Component 10",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 11000,
    outgoingPartNo: "FL-8910",
    outgoingRevision: "R0",
    outgoingDesc: "Legacy Fuel Component 10",
    outgoingQtyPerVehicle: 1,
    outgoingVehicleEndItem: "NA",
    outgoingCost: 8800,
    status: "Modify",
    remarks: "Emission optimization",
  },
],
"REQ-2024-010": [
  {
    id: "X-1",
    level: 1,
    system: "Misc",
    incomingPartNo: "MX-10001",
    incomingRevision: "R1",
    incomingDesc: "Miscellaneous Component 1",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 2500,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Platform standardization",
  },
  {
    id: "X-2",
    level: 1,
    system: "Misc",
    incomingPartNo: "MX-10002",
    incomingRevision: "R1",
    incomingDesc: "Miscellaneous Component 2",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 2750,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Platform standardization",
  },
  {
    id: "X-3",
    level: 1,
    system: "Misc",
    incomingPartNo: "MX-10003",
    incomingRevision: "R1",
    incomingDesc: "Miscellaneous Component 3",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 3000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Platform standardization",
  },
  {
    id: "X-4",
    level: 1,
    system: "Misc",
    incomingPartNo: "MX-10004",
    incomingRevision: "R1",
    incomingDesc: "Miscellaneous Component 4",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 3250,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Platform standardization",
  },
  {
    id: "X-5",
    level: 1,
    system: "Misc",
    incomingPartNo: "MX-10005",
    incomingRevision: "R1",
    incomingDesc: "Miscellaneous Component 5",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 3500,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Platform standardization",
  },
  {
    id: "X-6",
    level: 1,
    system: "Misc",
    incomingPartNo: "MX-10006",
    incomingRevision: "R1",
    incomingDesc: "Miscellaneous Component 6",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 3750,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Platform standardization",
  },
  {
    id: "X-7",
    level: 1,
    system: "Misc",
    incomingPartNo: "MX-10007",
    incomingRevision: "R1",
    incomingDesc: "Miscellaneous Component 7",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 4000,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Platform standardization",
  },
  {
    id: "X-8",
    level: 1,
    system: "Misc",
    incomingPartNo: "MX-10008",
    incomingRevision: "R1",
    incomingDesc: "Miscellaneous Component 8",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 4250,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Platform standardization",
  },
  {
    id: "X-9",
    level: 1,
    system: "Misc",
    incomingPartNo: "MX-10009",
    incomingRevision: "R1",
    incomingDesc: "Miscellaneous Component 9",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 4500,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Platform standardization",
  },
  {
    id: "X-10",
    level: 1,
    system: "Misc",
    incomingPartNo: "MX-10010",
    incomingRevision: "R1",
    incomingDesc: "Miscellaneous Component 10",
    incomingQtyPerVehicle: 1,
    incomingVehicleEndItem: "NA",
    incomingCost: 4750,
    outgoingPartNo: null,
    outgoingRevision: null,
    outgoingDesc: null,
    outgoingQtyPerVehicle: null,
    outgoingVehicleEndItem: null,
    outgoingCost: 0,
    status: "Add",
    remarks: "Platform standardization",
  },
],


};
